=encoding utf-8

=head1 NAME

Pg::RoundRobin - a simple round robin connection for PostgreSQL on top of DBIish

=head1 SYNOPSIS

    use v6;
    use Pg::RoundRobin;

    my $rr = Pg::RoundRobin.new(
                prefer_secondary => True, # if this set to True, primary node will not be used for read only
                dbservers =>
                (
                    [ :host<127.0.0.1>, :port<5432>, :database<heince>, :user<heince> ],
                    [ :host<127.0.0.1>, :port<5433>, :database<heince>, :user<heince> ],
                    [ :host<127.0.0.1>, :port<5434>, :database<heince>, :user<heince> ]
                )
             );
    $rr.init;

    # below will do round robin read only connection to all secondary node
    # if there's node fail it will try to the next possible secondary node
    OUTER: while True
    {
        my $dbh = $rr.secondary();
        next OUTER if $dbh eqv (Any);
        my $sth = $dbh.prepare("select * from test");
        $sth.execute();

        my @rows = $sth.allrows();
        $sth.finish();
        $dbh.dispose();

        for @rows -> ($id, $name)
        {
            say "id: $id, name: $name";
        }

        sleep 1;
    }

=head1 DESCRIPTION

This is a simple implementation of round robin failover connection on top of DBIish.
It will scan and group primary and secondary node accordingly at init.

=head1 DBIish CLASSES and ROLES

=head2 Pg::RoundRobin

The C<Pg::RoundRobin> class exists mainly to provide the F<init> method,
which acts as a constructor for database connections.
F<primary> will return DB Handle for primary node
F<secondary> will return DB Handle for secondary node

=head1 LICENSE

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
